# generated by datamodel-codegen:
#   filename:  sumJson.json
#   timestamp: 2023-07-23T00:15:28+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class ConnectedRealm(BaseModel):
    href: str


class Modifier(BaseModel):
    type: int
    value: int


class Item(BaseModel):
    id: int
    context: Optional[int] = None
    bonus_lists: Optional[List[int]] = None
    modifiers: Optional[List[Modifier]] = None
    pet_breed_id: Optional[int] = None
    pet_level: Optional[int] = None
    pet_quality_id: Optional[int] = None
    pet_species_id: Optional[int] = None


class Auction(BaseModel):
    id: int
    item: Item
    buyout: int
    quantity: int
    time_left: str
    bid: Optional[int] = None


class Commodities(BaseModel):
    href: str


class AuctionHouse(BaseModel):
    connected_realm: ConnectedRealm
    auctions: List[Auction]
    commodities: Commodities
